# ROOT = /home/ombt/ombt

ifndef ROOT
$(error ROOT is not set)
endif

include $(ROOT)/build/makefile.common

LIBNAME = gstring

HDRS = gstring.h gstring.cpp trie.h trie.cpp

include $(ROOT)/build/makefile.lib2
