#!/usr/bin/perl 
#
print "enter min number: ";
$min = <STDIN>;
chomp $min;
#
print "enter min number: ";
$max = <STDIN>;
chomp $max;
#
for ($i=$min; $i<=$max; $i++)
{
	print "$i*$i = " . $i*$i . "\n";
}
#
