all:	gp gp2 gp3 gp4 gp5

gp:	gp.cpp
	g++ -ogp gp.cpp -lrt

gp2:	gp2.cpp
	g++ -ogp2 gp2.cpp -lrt

gp3:	gp3.cpp
	g++ -ogp3 gp3.cpp -lrt

gp4:	gp4.cpp
	g++ -ogp4 gp4.cpp -lrt

gp5:	gp5.cpp
	g++ -ogp5 gp5.cpp -lrt

clean:
	-(rm -f gp gp2 gp3 gp4 gp5;)
