# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../..
endif

include $(ROOT)/build/makefile.common

PRODS = timer1 timer2 timer3 timer4 timer5

CXXEXTRAFLAGS = 
CXXLIBFLAGS = -lombttimers

include $(ROOT)/build/makefile.test
