#The CFLAGS variable will be passed from the top-level makefile.
#CFLAGS = -P -O2 -mc -DNEED_CAST

INCPATH = ..\..\include
LIBPATH = ..\..\lib
INCFLAGS = -I. -I$(INCPATH)
LIBS = aisearch.lib util.lib

TARGETS = parser.exe

OBJS = parser.obj data.obj run.obj

.cc.obj:
        $(CC) $(CFLAGS) $(INCFLAGS) -c $<

all:	$(TARGETS)

parser.exe:       $(OBJS)
        $(CC) $(CFLAGS) -L$(LIBPATH) $** $(LIBS)

