# ROOT = /home/ombt/ombt

ifndef ROOT
$(error ROOT is not set)
endif

include $(ROOT)/build/makefile.common

PRODS = tcubicspline

# CXXEXTRAFLAGS = -Wfatal-errors

include $(ROOT)/build/makefile.test
