# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../..
endif

include $(ROOT)/build/makefile.common

LIBNAME = numerics

HDRS = \
	Rational.h \
	Rational.cpp \
	SignedInteger.h \
	SignedInteger.cpp \
	UnsignedInteger.h \
	UnsignedInteger.cpp

include $(ROOT)/build/makefile.lib2
