# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../..
endif

include $(ROOT)/build/makefile.common

#SUBDIRS = \
#	gcalc \
#	gtk_tutorial \
#	qt_book \
#	qt_filewatcher \
#	qt_mdivwer \
#	qt_syncmgr

SUBDIRS = \
	gcalc \
	gtk_tutorial2

include $(ROOT)/build/makefile.subdirs
