#The CFLAGS variable will be passed from the top-level makefile.
#CFLAGS = -P -O2 -mc -DNEED_CAST

INCPATH = ..\..\include
LIBPATH = ..\..\lib
INCFLAGS = -I. -I$(INCPATH)
LIBS = aisearch.lib util.lib

TARGETS = prover.exe

OBJS = clause.obj ctable.obj literal.obj resnode.obj run.obj

.cc.obj:
        $(CC) $(CFLAGS) $(INCFLAGS) -c $<

all:	$(TARGETS)

prover.exe:       $(OBJS)
        $(CC) $(CFLAGS) -L$(LIBPATH) -e$< $** $(LIBS)

