# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/..
endif

include $(ROOT)/build/makefile.common

SUBDIRS = \
	atomic \
	logging \
	parsing \
	random \
	threads \
	adt \
	complex \
	matrix \
	numerics \
	interpolation \
	gstring \
	timers \
	sockets \
	signals \
	reactors \
	servers \
	distributions \
	files \
	graphs \
	logic

include $(ROOT)/build/makefile.libsubdirs
