
.SUFFIXES:		.o .C .CPP .c .cpp

LEXFLAGS = -n
YACC = /usr/ccs/bin/yacc
YACCFLAGS = -d -v
LEX = /usr/ccs/bin/lex
MAKE = make
LDFLAGS = 
TCLBIN = $(HOME)/bin
LD = cc
BACKUPDIR = BACKUP
SHELLBIN = $(HOME)/tools/bin
ARFLAGS = -r -v
CCFLAGS = -g
INCLDIRS = 
CC = cc
LPRFLAGS = 
AR = /usr/ccs/bin/ar
LPR = mycpr2on1
ENDLIST = 

.c.o:
		$(CC) $(CCFLAGS) $(INCLDIRS) -c $<
.C.o:
		$(CC) $(CCFLAGS) $(INCLDIRS) -c $<
.cpp.o:
		$(CC) $(CCFLAGS) $(INCLDIRS) -c $<
.CPP.o:
		$(CC) $(CCFLAGS) $(INCLDIRS) -c $<

all:		webcmhugpp \
		weblcsgench2ioms \
		webgetsploadsonly \
		webiomhugpp \
		webauditsps \
		weblcsbbbscripts \
		webdbquery \
		webnlcsstat \
		webcleanupsps \
		weblcspicks \
		webcpymems \
		webrecoversps \
		weblcsreboot \
		weblcssyncfs \
		webcpuhugpp \
		webrstallioms \
		webupdateioms \
		webgetsploads \
		weblcslocks \
		webtl1 \
		webrmvallioms \
		webposthugpp \
		webcpu_cmhugpp \
		weblcssyslog \
		webupsh \
		weblcsspaudit \
		webprehugpp \
		$(ENDLIST)
		touch all

webcmhugpp:		webcmhugpp.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webcmhugpp
		-cp webcmhugpp.sh webcmhugpp
		chmod +x webcmhugpp
		cp webcmhugpp $(SHELLBIN)/webcmhugpp

weblcsgench2ioms:		weblcsgench2ioms.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/weblcsgench2ioms
		-cp weblcsgench2ioms.sh weblcsgench2ioms
		chmod +x weblcsgench2ioms
		cp weblcsgench2ioms $(SHELLBIN)/weblcsgench2ioms

webgetsploadsonly:		webgetsploadsonly.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webgetsploadsonly
		-cp webgetsploadsonly.sh webgetsploadsonly
		chmod +x webgetsploadsonly
		cp webgetsploadsonly $(SHELLBIN)/webgetsploadsonly

webiomhugpp:		webiomhugpp.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webiomhugpp
		-cp webiomhugpp.sh webiomhugpp
		chmod +x webiomhugpp
		cp webiomhugpp $(SHELLBIN)/webiomhugpp

webauditsps:		webauditsps.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webauditsps
		-cp webauditsps.sh webauditsps
		chmod +x webauditsps
		cp webauditsps $(SHELLBIN)/webauditsps

weblcsbbbscripts:		weblcsbbbscripts.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/weblcsbbbscripts
		-cp weblcsbbbscripts.sh weblcsbbbscripts
		chmod +x weblcsbbbscripts
		cp weblcsbbbscripts $(SHELLBIN)/weblcsbbbscripts

webdbquery:		webdbquery.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webdbquery
		-cp webdbquery.sh webdbquery
		chmod +x webdbquery
		cp webdbquery $(SHELLBIN)/webdbquery

webnlcsstat:		webnlcsstat.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webnlcsstat
		-cp webnlcsstat.sh webnlcsstat
		chmod +x webnlcsstat
		cp webnlcsstat $(SHELLBIN)/webnlcsstat

webcleanupsps:		webcleanupsps.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webcleanupsps
		-cp webcleanupsps.sh webcleanupsps
		chmod +x webcleanupsps
		cp webcleanupsps $(SHELLBIN)/webcleanupsps

weblcspicks:		weblcspicks.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/weblcspicks
		-cp weblcspicks.sh weblcspicks
		chmod +x weblcspicks
		cp weblcspicks $(SHELLBIN)/weblcspicks

webcpymems:		webcpymems.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webcpymems
		-cp webcpymems.sh webcpymems
		chmod +x webcpymems
		cp webcpymems $(SHELLBIN)/webcpymems

webrecoversps:		webrecoversps.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webrecoversps
		-cp webrecoversps.sh webrecoversps
		chmod +x webrecoversps
		cp webrecoversps $(SHELLBIN)/webrecoversps

weblcsreboot:		weblcsreboot.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/weblcsreboot
		-cp weblcsreboot.sh weblcsreboot
		chmod +x weblcsreboot
		cp weblcsreboot $(SHELLBIN)/weblcsreboot

weblcssyncfs:		weblcssyncfs.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/weblcssyncfs
		-cp weblcssyncfs.sh weblcssyncfs
		chmod +x weblcssyncfs
		cp weblcssyncfs $(SHELLBIN)/weblcssyncfs

webcpuhugpp:		webcpuhugpp.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webcpuhugpp
		-cp webcpuhugpp.sh webcpuhugpp
		chmod +x webcpuhugpp
		cp webcpuhugpp $(SHELLBIN)/webcpuhugpp

webrstallioms:		webrstallioms.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webrstallioms
		-cp webrstallioms.sh webrstallioms
		chmod +x webrstallioms
		cp webrstallioms $(SHELLBIN)/webrstallioms

webupdateioms:		webupdateioms.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webupdateioms
		-cp webupdateioms.sh webupdateioms
		chmod +x webupdateioms
		cp webupdateioms $(SHELLBIN)/webupdateioms

webgetsploads:		webgetsploads.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webgetsploads
		-cp webgetsploads.sh webgetsploads
		chmod +x webgetsploads
		cp webgetsploads $(SHELLBIN)/webgetsploads

weblcslocks:		weblcslocks.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/weblcslocks
		-cp weblcslocks.sh weblcslocks
		chmod +x weblcslocks
		cp weblcslocks $(SHELLBIN)/weblcslocks

webtl1:		webtl1.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webtl1
		-cp webtl1.sh webtl1
		chmod +x webtl1
		cp webtl1 $(SHELLBIN)/webtl1

webrmvallioms:		webrmvallioms.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webrmvallioms
		-cp webrmvallioms.sh webrmvallioms
		chmod +x webrmvallioms
		cp webrmvallioms $(SHELLBIN)/webrmvallioms

webposthugpp:		webposthugpp.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webposthugpp
		-cp webposthugpp.sh webposthugpp
		chmod +x webposthugpp
		cp webposthugpp $(SHELLBIN)/webposthugpp

webcpu_cmhugpp:		webcpu_cmhugpp.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webcpu_cmhugpp
		-cp webcpu_cmhugpp.sh webcpu_cmhugpp
		chmod +x webcpu_cmhugpp
		cp webcpu_cmhugpp $(SHELLBIN)/webcpu_cmhugpp

weblcssyslog:		weblcssyslog.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/weblcssyslog
		-cp weblcssyslog.sh weblcssyslog
		chmod +x weblcssyslog
		cp weblcssyslog $(SHELLBIN)/weblcssyslog

webupsh:		webupsh.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webupsh
		-cp webupsh.sh webupsh
		chmod +x webupsh
		cp webupsh $(SHELLBIN)/webupsh

weblcsspaudit:		weblcsspaudit.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/weblcsspaudit
		-cp weblcsspaudit.sh weblcsspaudit
		chmod +x weblcsspaudit
		cp weblcsspaudit $(SHELLBIN)/weblcsspaudit

webprehugpp:		webprehugpp.sh \
		$(ENDLIST)
		-rm -f $(SHELLBIN)/webprehugpp
		-cp webprehugpp.sh webprehugpp
		chmod +x webprehugpp
		cp webprehugpp $(SHELLBIN)/webprehugpp

clean:
		-([ -f "ir.out" ] && rm -rf ir.out;)
		-rm -f webcmhugpp
		-rm -f weblcsgench2ioms
		-rm -f webgetsploadsonly
		-rm -f webiomhugpp
		-rm -f webauditsps
		-rm -f weblcsbbbscripts
		-rm -f webdbquery
		-rm -f webnlcsstat
		-rm -f webcleanupsps
		-rm -f weblcspicks
		-rm -f webcpymems
		-rm -f webrecoversps
		-rm -f weblcsreboot
		-rm -f weblcssyncfs
		-rm -f webcpuhugpp
		-rm -f webrstallioms
		-rm -f webupdateioms
		-rm -f webgetsploads
		-rm -f weblcslocks
		-rm -f webtl1
		-rm -f webrmvallioms
		-rm -f webposthugpp
		-rm -f webcpu_cmhugpp
		-rm -f weblcssyslog
		-rm -f webupsh
		-rm -f weblcsspaudit
		-rm -f webprehugpp

backup:		weblcssyslog.sh \
		weblcsgench2ioms.sh \
		webdbquery.sh \
		webcpuhugpp.sh \
		webrecoversps.sh \
		webcmhugpp.sh \
		webgetsploads.sh \
		webposthugpp.sh \
		webrstallioms.sh \
		webiomhugpp.sh \
		webcpu_cmhugpp.sh \
		webgetsploadsonly.sh \
		webnlcsstat.sh \
		webupsh.sh \
		weblcslocks.sh \
		webrmvallioms.sh \
		weblcsreboot.sh \
		weblcspicks.sh \
		webupdateioms.sh \
		webtl1.sh \
		weblcssyncfs.sh \
		weblcsspaudit.sh \
		webcleanupsps.sh \
		webcpymems.sh \
		webprehugpp.sh \
		webauditsps.sh \
		weblcsbbbscripts.sh \
		$(ENDLIST)
		-([ ! -d "./$(BACKUPDIR)" ] && mkdir ./$(BACKUPDIR);)
		cp weblcssyslog.sh $(BACKUPDIR)/weblcssyslog.sh
		cp weblcsgench2ioms.sh $(BACKUPDIR)/weblcsgench2ioms.sh
		cp webdbquery.sh $(BACKUPDIR)/webdbquery.sh
		cp webcpuhugpp.sh $(BACKUPDIR)/webcpuhugpp.sh
		cp webrecoversps.sh $(BACKUPDIR)/webrecoversps.sh
		cp webcmhugpp.sh $(BACKUPDIR)/webcmhugpp.sh
		cp webgetsploads.sh $(BACKUPDIR)/webgetsploads.sh
		cp webposthugpp.sh $(BACKUPDIR)/webposthugpp.sh
		cp webrstallioms.sh $(BACKUPDIR)/webrstallioms.sh
		cp webiomhugpp.sh $(BACKUPDIR)/webiomhugpp.sh
		cp webcpu_cmhugpp.sh $(BACKUPDIR)/webcpu_cmhugpp.sh
		cp webgetsploadsonly.sh $(BACKUPDIR)/webgetsploadsonly.sh
		cp webnlcsstat.sh $(BACKUPDIR)/webnlcsstat.sh
		cp webupsh.sh $(BACKUPDIR)/webupsh.sh
		cp weblcslocks.sh $(BACKUPDIR)/weblcslocks.sh
		cp webrmvallioms.sh $(BACKUPDIR)/webrmvallioms.sh
		cp weblcsreboot.sh $(BACKUPDIR)/weblcsreboot.sh
		cp weblcspicks.sh $(BACKUPDIR)/weblcspicks.sh
		cp webupdateioms.sh $(BACKUPDIR)/webupdateioms.sh
		cp webtl1.sh $(BACKUPDIR)/webtl1.sh
		cp weblcssyncfs.sh $(BACKUPDIR)/weblcssyncfs.sh
		cp weblcsspaudit.sh $(BACKUPDIR)/weblcsspaudit.sh
		cp webcleanupsps.sh $(BACKUPDIR)/webcleanupsps.sh
		cp webcpymems.sh $(BACKUPDIR)/webcpymems.sh
		cp webprehugpp.sh $(BACKUPDIR)/webprehugpp.sh
		cp webauditsps.sh $(BACKUPDIR)/webauditsps.sh
		cp weblcsbbbscripts.sh $(BACKUPDIR)/weblcsbbbscripts.sh
		touch backup

backupd:		weblcssyslog.sh \
		weblcsgench2ioms.sh \
		webdbquery.sh \
		webcpuhugpp.sh \
		webrecoversps.sh \
		webcmhugpp.sh \
		webgetsploads.sh \
		webposthugpp.sh \
		webrstallioms.sh \
		webiomhugpp.sh \
		webcpu_cmhugpp.sh \
		webgetsploadsonly.sh \
		webnlcsstat.sh \
		webupsh.sh \
		weblcslocks.sh \
		webrmvallioms.sh \
		weblcsreboot.sh \
		weblcspicks.sh \
		webupdateioms.sh \
		webtl1.sh \
		weblcssyncfs.sh \
		weblcsspaudit.sh \
		webcleanupsps.sh \
		webcpymems.sh \
		webprehugpp.sh \
		webauditsps.sh \
		weblcsbbbscripts.sh \
		$(ENDLIST)
		-([ ! -d "./$(BACKUPDIR)" ] && mkdir ./$(BACKUPDIR);)
		backup -d
		touch backupd

mymk:
		mymk

print:		weblcssyslog.sh \
		weblcsgench2ioms.sh \
		webdbquery.sh \
		webcpuhugpp.sh \
		webrecoversps.sh \
		webcmhugpp.sh \
		webgetsploads.sh \
		webposthugpp.sh \
		webrstallioms.sh \
		webiomhugpp.sh \
		webcpu_cmhugpp.sh \
		webgetsploadsonly.sh \
		webnlcsstat.sh \
		webupsh.sh \
		weblcslocks.sh \
		webrmvallioms.sh \
		weblcsreboot.sh \
		weblcspicks.sh \
		webupdateioms.sh \
		webtl1.sh \
		weblcssyncfs.sh \
		weblcsspaudit.sh \
		webcleanupsps.sh \
		webcpymems.sh \
		webprehugpp.sh \
		webauditsps.sh \
		weblcsbbbscripts.sh \
		$(ENDLIST)
		$(LPR) $(LPRFLAGS) \
			weblcssyslog.sh \
			weblcsgench2ioms.sh \
			webdbquery.sh \
			webcpuhugpp.sh \
			webrecoversps.sh \
			webcmhugpp.sh \
			webgetsploads.sh \
			webposthugpp.sh \
			webrstallioms.sh \
			webiomhugpp.sh \
			webcpu_cmhugpp.sh \
			webgetsploadsonly.sh \
			webnlcsstat.sh \
			webupsh.sh \
			weblcslocks.sh \
			webrmvallioms.sh \
			weblcsreboot.sh \
			weblcspicks.sh \
			webupdateioms.sh \
			webtl1.sh \
			weblcssyncfs.sh \
			weblcsspaudit.sh \
			webcleanupsps.sh \
			webcpymems.sh \
			webprehugpp.sh \
			webauditsps.sh \
			weblcsbbbscripts.sh \
			$(ENDLIST)
