#The CFLAGS variable will be handed down from the top-level makefile.
#CFLAGS = -P -O2 -mc -DNEED_CAST

AR = tlib 
AILIB = ..\..\lib\aisearch.lib
INCFLAGS = -I..\..\include

.cc.obj:
        $(CC) $(CFLAGS) $(INCFLAGS) -c $*.cc
        $(AR) $(AILIB) -+$*

OBJS = node.obj andnode.obj aonode.obj backnode.obj bnode.obj dnode.obj ornode.obj unode.obj

all:	$(OBJS)

