C
C BASIC RULES FOR FORTRAN:
C
C 0) ONLY USE CAPITAL LETTERS.
C 1) VARIABLE NAMES MUST BE 6 CHARACTERS OR LESS. 
C 2) THE VARIABLE CAN ONLY CONTAIN LETTERS OR NUMBERS.
C 3) DECLARE ALL VARIABLES BEFORE YOU USE THEM.
C 4) A LETTER "C" IN COLUMN 1 INDICATES A COMMENT.
C 5) FORTRAN INSTRUCTIONS MUST BE TYPE BETWEEN COLUMNS
C    7 AND 72 INCLUSIVE.
C 6) LETTER IN COLUMN 6 INDICATES A CONTINUATION LINE.
C
C PROBLEM DESCRIPTION:
C
C THIS PROGRAM IS AN EXAMPLE OF HOW TO USE AN IF-STATEMENT AND 
C A COUNTING-LOOP (A DO-LOOP). THE PROGRAM SIMPLY COUNTS. IT READS
C IN START AND END VALUES. THE PROGRAM DECIDES IF IT HAS TO COUNT
C DOWN (9,8,7,...) OR IF NEEDS TO COUNT UP (1,2,3,...).
C
C        1         2         3         4         5         6         7
C23456789012345678901234567890123456789012345678901234567890123456789012
C
      PROGRAM COUNT
C
C DECLARE VARIABLES.
C
      INTEGER START, END, INCR, IDX
C
C GET START AND END VALUES FROM USER.
C
 10   PRINT *, 'ENTER START AND END VALUES: '
      READ *, START, END
C
C DETERMINE IF TO COUNT DOWN OR UP.
C
      IF (START.GT.END) THEN
          PRINT *, 'WILL COUNT DOWN !!!'
          INCR = -1
      ELSE
          PRINT *, 'WILL COUNT UP !!!'
          INCR = 1
      ENDIF
C
C COUNT !!!
C
      DO IDX=START, END, INCR
          PRINT *, 'NUMBER IS ... ', IDX
      END DO
C
C ALL DONE
C
      END
