# ROOT = /home/ombt/ombt

ifndef ROOT
$(error ROOT is not set)
endif

include $(ROOT)/build/makefile.common

LIBNAME = atomic

HDRS = \
	Atomic.h \
	BaseObject.h \
	UseCntBase.h \
	UseCntPtr.h \
	NIUseCntPtr.h

include $(ROOT)/build/makefile.lib2

