#
# Copyright (C) 2010, OMBT LLC and Mike A. Rumore
# All rights reserved.
# Contact: Mike A. Rumore, (mike.a.rumore@gmail.com)
#
# ROOT = /home/ombt/ombt

ifndef ROOT
$(error ROOT is not set)
endif

include $(ROOT)/build/makefile.common

LIBNAME = atomic

HDRS = \
	Atomic.h \
	BaseObject.h \
	UseCntBase.h \
	UseCntPtr.h \
	NIUseCntPtr.h

include $(ROOT)/build/makefile.lib2

