C
C BASIC RULES FOR FORTRAN:
C
C 0) ONLY USE CAPITAL LETTERS.
C 1) VARIABLE NAMES MUST BE 6 CHARACTERS OR LESS. 
C 2) THE VARIABLE CAN ONLY CONTAIN LETTERS OR NUMBERS.
C 3) DECLARE ALL VARIABLES BEFORE YOU USE THEM.
C 4) A LETTER "C" IN COLUMN 1 INDICATES A COMMENT.
C 5) FORTRAN INSTRUCTIONS MUST BE TYPE BETWEEN COLUMNS
C    7 AND 72 INCLUSIVE.
C 6) LETTER IN COLUMN 6 INDICATES A CONTINUATION LINE.
C
C PROBLEM DESCRIPTION:
C
C THIS PROGRAM IS AN EXAMPLE OF HOW TO USE AN IF-STATEMENT. THE 
C PROBLEM IS TO CONVERT FAHRENHEIT TO CELSIUS OR VICE-VERSA.
C
C        1         2         3         4         5         6         7
C23456789012345678901234567890123456789012345678901234567890123456789012
C
      PROGRAM TEMP
C
C DECLARE VARIABLES.
C
      CHARACTER INTYPE
      CHARACTER*20 OUTTYPE
      REAL DEGREES
C
C GET TYPE OF TEMPERATURE FROM USER.
C
 10   PRINT *, 'TEMPERATURE TYPE, ENTER C OR F: '
      READ *, INTYPE
C
C DETERMINE THE TYPE.
C
      IF (INTYPE.EQ.'C') THEN
          PRINT *, 'ENTER DEGREES CELSIUS: '
          READ *, DEGREES
          DEGREES = 9.0*DEGREES/5.0 + 32.0
          OUTTYPE = 'FAHRENHEIT'
      ELSE IF (INTYPE.EQ.'F') THEN
          PRINT *, 'ENTER DEGREES FAHRENHEIT: '
          READ *, DEGREES
          DEGREES = 5.0*(DEGREES - 32.0)/9.0
          OUTTYPE = 'CELSIUS'
      ELSE
          PRINT *, 'ERROR: ENTER C OR F. TRY AGAIN.'
          GOTO 10
      ENDIF
C
C PRINT RESULT.
C
      PRINT *, 'TEMPERATURE IS ', DEGREES, ' ', OUTTYPE
C
C ALL DONE
C
      END
