C
C BASIC RULES FOR FORTRAN:
C
C 0) ONLY USE CAPITAL LETTERS.
C 1) VARIABLE NAMES MUST BE 6 CHARACTERS OR LESS. 
C 2) THE VARIABLE CAN ONLY CONTAIN LETTERS OR NUMBERS.
C 3) DECLARE ALL VARIABLES BEFORE YOU USE THEM.
C 4) A LETTER "C" IN COLUMN 1 INDICATES A COMMENT.
C 5) FORTRAN INSTRUCTIONS MUST BE TYPE BETWEEN COLUMNS
C    7 AND 72 INCLUSIVE.
C 6) LETTER IN COLUMN 6 INDICATES A CONTINUATION LINE.
C
C PROBLEM DESCRIPTION:
C
C THIS PROGRAM IS AN EXAMPLE OF HOW TO USE AN IF-STATEMENT AND 
C A COUNTING-LOOP (A DO-LOOP). THIS PROGRAM PRINTS A LIST OF
C SINE VALUES FOR A RANGE OF ANGLES. IT READS IN THE START AND END
C ANGLES IN DEGREES OR RADIANS AND GENERATES A LIST OF SINE VALUES 
C IN STEPS OF 1 DEGREE OR 0.1 RADIANS.
C
C        1         2         3         4         5         6         7
C23456789012345678901234567890123456789012345678901234567890123456789012
C
      PROGRAM SINE
C
C DECLARE PARAMETER.
C
      REAL PI
      PARAMETER(PI=3.14159)
C
C DECLARE VARIABLES.
C
      REAL MIN, MAX
      INTEGER START, END
      CHARACTER*20 TYPE
C
C GET START AND END ANGLES FROM USER.
C
 10   PRINT *, '(D)EGREES OR (R)ADIANS? '
      READ *, TYPE
      IF (TYPE(1:1).EQ.'D') THEN
          TYPE = 'DEGREES'
      ELSE IF (TYPE(1:1).EQ.'R') THEN
          TYPE = 'RADIANS'
      ELSE
          PRINT *, 'OOPS!!! TRY AGAIN !!!'
          GOTO 10
      ENDIF
C
 20   PRINT *, 'ENTER START AND END ANGLES IN ', TYPE, ':'
      READ *, MIN, MAX
C
C CHECK ANGLES.
C
      IF (MIN.GT.MAX) THEN
          PRINT *, 'START ANGLE GREATER THAN END ANGLE'
          PRINT *, 'TRY AGAIN.'
          GOTO 20
      ENDIF
C
C GENERATE SINE TABLE.
C
      IF (TYPE(1:1).EQ.'D') THEN
C
C USE DEGREES.
C
          START = MIN
          END = MAX
C
          DO IDX=START, END
              PRINT *, 'SINE(', IDX, ') = ', SIN(IDX*PI/180.0)
          END DO
      ELSE
C
C USE RADIANS.
C
          START = MIN/0.1
          END = MAX/0.1
C
          DO IDX=START, END
              PRINT *, 'SINE(', IDX*0.1, ') = ', SIN(IDX*0.1)
          END DO
      ENDIF
C
C ALL DONE
C
      END
