C
C BASIC RULES FOR FORTRAN:
C
C 0) ONLY USE CAPITAL LETTERS.
C 1) VARIABLE NAMES MUST BE 6 CHARACTERS OR LESS. 
C 2) THE VARIABLE CAN ONLY CONTAIN LETTERS OR NUMBERS.
C 3) DECLARE ALL VARIABLES BEFORE YOU USE THEM.
C 4) A LETTER "C" IN COLUMN 1 INDICATES A COMMENT.
C 5) FORTRAN INSTRUCTIONS MUST BE TYPE BETWEEN COLUMNS
C    7 AND 72 INCLUSIVE.
C
C
C READ IN QUADRATIC COEFFICIENTS AND FIND ROOTS. USE QUADRATIC
C FORMULA TO SOLVE. USE DETERMINANT TO DETERMINE THE TYPE OF
C ROOTS.
C
C A*X**2 + B*X + C = 0
C
C X1 = (-B + SQRT(B**2 - 4*A*C))/(2*A)
C X2 = (-B - SQRT(B**2 - 4*A*C))/(2*A)
C
C        1         2         3         4         5         6         7
C23456789012345678901234567890123456789012345678901234567890123456789012
C
      PROGRAM QUAD
C
C DECLARE VARIABLES.
C
      INTEGER I, IMAX
      REAL DET, A, B, C, X1, X2
      REAL XR, XI
C
C READ FROM USER THE NUMBER OF SETS TO READ IN.
C
      PRINT *, 'HOW MANY SETS OF COEFFICIENTS TO READ IN ?'
      READ *, IMAX
C
C LOOP THRU THE REQUIRED NUMBER OF TIMES.
C
      DO 1000 I=1, IMAX, 1
C
C READ IN COEFFICIENTS.
C
          PRINT *, 'ENTER SET ', I, ' OF COEF. A, B, C'
          READ *, A, B, C
C
C DETERMINE THE TYPE OF ROOTS.
C
          DET = B*B - 4.0*A*C
C
          IF (DET.LT.0.0) THEN
              PRINT *, 'ROOTS ARE COMPLEX'
              XR = (-B)/(2*A)
              XI = (ABS(DET)**0.5)/(2*A)
              PRINT *, 'ROOT X1 IS: ', XR, ' + ', XI, '*i'
              PRINT *, 'ROOT X2 IS: ', XR, ' - ', XI, '*i'
          ELSE IF (DET.GT.0.0) THEN
              PRINT *, 'ROOTS ARE REAL AND UNEQUAL'
              X1 = (-B + DET**0.5)/(2*A)
              X2 = (-B - DET**0.5)/(2*A)
              PRINT *, 'ROOTS ARE: ', X1, X2
          ELSE
              PRINT *, 'ROOTS ARE REAL AND EQUAL'
              X1 = (-B)/(2*A)
              PRINT *, 'ROOT IS: ', X1
          ENDIF
C
C
 1000 CONTINUE
C
C ALL DONE
C
      END
