all:
	-(cd pp; make all;)
	-(cd fe; make all;)
	-(cd split; make all;)
	-(cd pr; make all;)
	-(cd sh; make all;)

mymk:
	-(cd pp; mymk;)
	-(cd fe; mymk;)
	-(cd split; mymk;)
	-(cd pr; mymk;)
	-(cd sh; mymk;)

backup:
	-(cd pp; make backup;)
	-(cd fe; make backup;)
	-(cd split; make backup;)
	-(cd pr; make backup;)
	-(cd sh; make backup;)

clean:
	-(cd pp; make clean;)
	-(cd fe; make clean;)
	-(cd split; make clean;)
	-(cd pr; make clean;)
	-(cd sh; make clean;)

print:
	-(cd pp; make print;)
	-(cd fe; make print;)
	-(cd split; make print;)
	-(cd pr; make print;)
	-(cd sh; make print;)

