#
# Copyright (C) 2010, OMBT LLC and Mike A. Rumore
# All rights reserved.
# Contact: Mike A. Rumore, (mike.a.rumore@gmail.com)
#
basecalc:	basecalc.c
		cc -DSysV -g -I. -I/opt/x11r5/include -o basecalc \
			basecalc.c \
			-lX11
