all:	gp gp2 gp3 gp4 gp5

gp:	gp.cpp
	g++ -ogp -lrt gp.cpp

gp2:	gp2.cpp
	g++ -ogp2 -lrt gp2.cpp

gp3:	gp3.cpp
	g++ -ogp3 -lrt gp3.cpp

gp4:	gp4.cpp
	g++ -ogp4 -lrt gp4.cpp

gp5:	gp5.cpp
	g++ -ogp5 -lrt gp5.cpp

clean:
	-(rm -f gp gp2 gp3 gp4 gp5;)
