#!/usr/bin/perl -w
#
$foo = 42;
print "foo is .. $foo\n";
#
$pfoo = \$foo;
print "pfoo is .. $pfoo\n";
print "contents of pfoo is .. $$pfoo\n";
#
print "\n";
#
@array = (1, 3, 5);
print "array is .. @array\n";
#
$parray = \@array;
print "parray is .. $parray\n";
print "contents of parray is .. @$parray\n";
#
exit 0

