#include <stdio.h>
#include <stdlib.h>
#include <inttypes.h>
# define U(x) x
# define NLSTATE yyprevious=YYNEWLINE
# define BEGIN yybgin = yysvec + 1 +
# define INITIAL 0
# define YYLERR yysvec
# define YYSTATE (yyestate-yysvec-1)
# define YYOPTIM 1
# ifndef YYLMAX 
# define YYLMAX BUFSIZ
# endif 
#ifndef __cplusplus
# define output(c) (void)putc(c,yyout)
#else
# define lex_output(c) (void)putc(c,yyout)
#endif

#if defined(__cplusplus) || defined(__STDC__)

#if defined(__cplusplus) && defined(__EXTERN_C__)
extern "C" {
#endif
	int yyback(int *, int);
	int yyinput(void);
	int yylook(void);
	void yyoutput(int);
	int yyracc(int);
	int yyreject(void);
	void yyunput(int);
	int yylex(void);
#ifdef YYLEX_E
	void yywoutput(wchar_t);
	wchar_t yywinput(void);
#endif
#ifndef yyless
	int yyless(int);
#endif
#ifndef yywrap
	int yywrap(void);
#endif
#ifdef LEXDEBUG
	void allprint(char);
	void sprint(char *);
#endif
#if defined(__cplusplus) && defined(__EXTERN_C__)
}
#endif

#ifdef __cplusplus
extern "C" {
#endif
	void exit(int);
#ifdef __cplusplus
}
#endif

#endif
# define unput(c) {yytchar= (c);if(yytchar=='\n')yylineno--;*yysptr++=yytchar;}
# define yymore() (yymorfg=1)
#ifndef __cplusplus
# define input() (((yytchar=yysptr>yysbuf?U(*--yysptr):getc(yyin))==10?(yylineno++,yytchar):yytchar)==EOF?0:yytchar)
#else
# define lex_input() (((yytchar=yysptr>yysbuf?U(*--yysptr):getc(yyin))==10?(yylineno++,yytchar):yytchar)==EOF?0:yytchar)
#endif
#define ECHO fprintf(yyout, "%s",yytext)
# define REJECT { nstr = yyreject(); goto yyfussy;}
int yyleng;
#define YYISARRAY
char yytext[YYLMAX];
int yymorfg;
extern char *yysptr, yysbuf[];
int yytchar;
FILE *yyin = {stdin}, *yyout = {stdout};
extern int yylineno;
struct yysvf { 
	struct yywork *yystoff;
	struct yysvf *yyother;
	int *yystops;};
struct yysvf *yyestate;
extern struct yysvf yysvec[], *yybgin;
// first-order logic language tokenizer
//
// language consists of the following symbols:
//
// constants:	a, b, c, ...
// variables:	x, y, z, ...
// functions:	f, g, h, ...
// predicates:	P, Q, R, ...
//
// functions and predicates can have a list of arguments, such as:
//
// f(a, b, c) or P(a, b, c)
//
// a function maps a list of constants to a constant.
//
// terms are defined recursively as follows:
//
// 1) a constant is a term.
// 2) a variable is a term.
// 3) if f is an n-place function, and t1, ..., tn are terms, then
// f(t1,...,tn) is a term.
// 4) nothing else is a term.
//
// a predicate is mapping of a list of constants to True or False.
//
// if P is an n-place predicate and t1, ..., tn are terms, then
// P(t1,...,tn) is an atom. Nothing else is an atom.
//
// well-formed formulas, WFF, are built as follows:
//
// 1) an atom is a formula.
// 2) if F and G are formulas, then the following are formulas:
//
//	1) ~F
//	2) F || G
//	3) F && G
//	4) F --> G
//	5) F <--> G
//
// 3) If F is a formula and x is a variable free in F, then the following
// 	are formulas:
//
//	1) forall(x)F(x) or <x>F(x) (universal instantiation)
//	2) forsome(x)F(x) or [x]F(x) (existential instantiation)
//
// additional notation:
//
//	(, )  - parenthesis for grouping.
//	|- - "therefore ..."
//	?- - "query for ..."
//
// the language defined for this prover has a few "C"-isms, the
// operators are from C, and all lines must be terminated with a
// semicolon.
//
/////////////////////////////////////////////////////////////////////
//

// headers
#include "folp.h"

// definitions generated by yacc
#include "folpyacc.h"

// other macros
#ifdef YYDEBUG
#define YYDUMP() fprintf(stdout, "token is <%s>.\n", yytext)
#else
#define YYDUMP()
#endif

#define IFECHO if (echo) ECHO

#define GETTOKEN(tokenId) { \
	IFECHO; \
	YYDUMP(); \
	strcpy(yylval.cstring, yytext); \
	return(tokenId); \
}

# define YYNEWLINE 10
yylex(){
int nstr; extern int yyprevious;
#ifdef __cplusplus
/* to avoid CC and lint complaining yyfussy not being used ...*/
static int __lex_hack = 0;
if (__lex_hack) goto yyfussy;
#endif
while((nstr = yylook()) >= 0)
yyfussy: switch(nstr){
case 0:
if(yywrap()) return(0); break;
case 1:

# line 93 "folp.l"
IFECHO;
break;
case 2:

# line 94 "folp.l"
	IFECHO;
break;
case 3:

# line 95 "folp.l"
IFECHO;
break;
case 4:

# line 97 "folp.l"
	GETTOKEN(THEREFORE);
break;
case 5:

# line 98 "folp.l"
	GETTOKEN(QUERY);
break;
case 6:

# line 99 "folp.l"
	GETTOKEN(BICONDITIONAL);
break;
case 7:

# line 100 "folp.l"
	GETTOKEN(IMPLICATION);
break;
case 8:

# line 101 "folp.l"
	GETTOKEN(OR);
break;
case 9:

# line 102 "folp.l"
	GETTOKEN(AND);
break;
case 10:

# line 103 "folp.l"
	GETTOKEN(NEGATION);
break;
case 11:

# line 104 "folp.l"
	GETTOKEN(LPAREN);
break;
case 12:

# line 105 "folp.l"
	GETTOKEN(RPAREN);
break;
case 13:

# line 106 "folp.l"
	GETTOKEN(COLON);
break;
case 14:

# line 107 "folp.l"
	GETTOKEN(COMMA);
break;
case 15:

# line 108 "folp.l"
	GETTOKEN(SEMICOLON);
break;
case 16:

# line 109 "folp.l"
GETTOKEN(UNIVERSAL);
break;
case 17:

# line 110 "folp.l"
	GETTOKEN(LEFTUNIVERSAL);
break;
case 18:

# line 111 "folp.l"
	GETTOKEN(RIGHTUNIVERSAL);
break;
case 19:

# line 112 "folp.l"
GETTOKEN(EXISTENTIAL);
break;
case 20:

# line 113 "folp.l"
	GETTOKEN(LEFTEXISTENTIAL);
break;
case 21:

# line 114 "folp.l"
	GETTOKEN(RIGHTEXISTENTIAL);
break;
case 22:

# line 115 "folp.l"
	GETTOKEN(LBRACE);
break;
case 23:

# line 116 "folp.l"
	GETTOKEN(RBRACE);
break;
case 24:

# line 117 "folp.l"
	GETTOKEN(EQUAL);
break;
case 25:

# line 118 "folp.l"
	GETTOKEN(NOTEQUAL);
break;
case 26:

# line 119 "folp.l"
GETTOKEN(ARGUMENT);
break;
case 27:

# line 120 "folp.l"
	GETTOKEN(QUIT);
break;
case 28:

# line 121 "folp.l"
	GETTOKEN(TRUE);
break;
case 29:

# line 122 "folp.l"
	GETTOKEN(FALSE);
break;
case 30:

# line 123 "folp.l"
	GETTOKEN(SOS);
break;
case 31:

# line 124 "folp.l"
GETTOKEN(OPTION);
break;
case 32:

# line 125 "folp.l"
GETTOKEN(NUMBER);
break;
case 33:

# line 126 "folp.l"
	GETTOKEN(MINUS);
break;
case 34:

# line 128 "folp.l"
{
		IFECHO;
		YYDUMP();
		yytext[strlen(yytext)-1] = 0;
		strcpy(yylval.cstring, yytext+1);
		return(STRING);
		}
break;
case 35:

# line 135 "folp.l"
GETTOKEN(IDENTIFIER);
break;
case 36:

# line 136 "folp.l"
GETTOKEN(PIDENTIFIER);
break;
case 37:

# line 137 "folp.l"
	{
		IFECHO;
		YYDUMP();
		strcpy(yylval.cstring, yytext);
		return(*yytext);
		}
break;
case -1:
break;
default:
(void)fprintf(yyout,"bad switch yylook %d",nstr);
} return(0); }
/* end of yylex */

# line 145 "folp.l"

// useless function
int
yywrap(void)
{
	return(1);
}

#if 0
main(int argc, char **argv)
{
	extern FILE *yyin;

	// tokenize a list of files
	for (int arg = 1; arg < argc; arg++)
	{
		// tell which file is scanned
		cout << "scanning file ... " << argv[arg] << endl;

		// open file to scan
		if ((yyin = fopen(argv[arg], "r")) == NULL)
		{
			ERRORD("fopen failed.", argv[arg], errno);
			continue;
		}

		// call scanner
		while (yylex() != 0) ;
	}

	// all done
	return(0);
}
#endif




int yyvstop[] = {
0,

37,
0, 

1,
37,
0, 

3,
0, 

37,
0, 

37,
0, 

37,
0, 

37,
0, 

11,
37,
0, 

12,
37,
0, 

14,
37,
0, 

33,
37,
0, 

32,
37,
0, 

13,
37,
0, 

15,
37,
0, 

17,
37,
0, 

24,
37,
0, 

18,
37,
0, 

37,
0, 

36,
37,
0, 

36,
37,
0, 

20,
37,
0, 

21,
37,
0, 

35,
37,
0, 

35,
37,
0, 

35,
37,
0, 

35,
37,
0, 

35,
37,
0, 

35,
37,
0, 

22,
37,
0, 

37,
0, 

23,
37,
0, 

10,
37,
0, 

1,
0, 

25,
0, 

34,
0, 

2,
0, 

9,
0, 

32,
0, 

5,
0, 

36,
0, 

36,
0, 

35,
0, 

35,
0, 

35,
0, 

35,
0, 

35,
0, 

35,
0, 

35,
0, 

4,
0, 

8,
0, 

7,
0, 

30,
36,
0, 

35,
0, 

35,
0, 

35,
0, 

35,
0, 

35,
0, 

35,
0, 

6,
0, 

35,
0, 

35,
0, 

35,
0, 

35,
0, 

35,
0, 

27,
35,
0, 

28,
35,
0, 

35,
0, 

29,
35,
0, 

35,
0, 

35,
0, 

35,
0, 

35,
0, 

16,
35,
0, 

35,
0, 

35,
0, 

35,
0, 

19,
35,
0, 

31,
35,
0, 

26,
35,
0, 
0};
# define YYTYPE unsigned char
struct yywork { YYTYPE verify, advance; } yycrank[] = {
0,0,	0,0,	1,3,	0,0,	
0,0,	0,0,	0,0,	0,0,	
0,0,	0,0,	1,4,	1,5,	
0,0,	0,0,	4,35,	0,0,	
0,0,	0,0,	0,0,	0,0,	
0,0,	0,0,	0,0,	0,0,	
0,0,	0,0,	0,0,	0,0,	
0,0,	0,0,	0,0,	0,0,	
0,0,	0,0,	1,6,	1,7,	
1,8,	4,35,	0,0,	1,9,	
9,41,	1,10,	1,11,	0,0,	
0,0,	1,12,	1,13,	17,44,	
20,45,	1,14,	44,58,	0,0,	
0,0,	0,0,	0,0,	0,0,	
0,0,	0,0,	32,55,	1,15,	
1,16,	1,17,	1,18,	1,19,	
1,20,	6,36,	1,21,	13,42,	
42,57,	58,66,	13,43,	13,43,	
13,43,	13,43,	13,43,	13,43,	
13,43,	13,43,	13,43,	13,43,	
22,47,	0,0,	0,0,	0,0,	
1,22,	47,59,	0,0,	0,0,	
0,0,	0,0,	0,0,	0,0,	
1,23,	0,0,	1,24,	0,0,	
1,3,	0,0,	1,25,	1,26,	
1,26,	1,26,	1,26,	1,27,	
1,26,	1,26,	1,26,	1,26,	
1,26,	1,26,	1,26,	1,26,	
1,28,	1,26,	1,29,	1,26,	
1,26,	1,30,	1,26,	1,26,	
1,26,	1,26,	1,26,	1,26,	
1,31,	1,32,	1,33,	1,34,	
2,6,	26,48,	2,8,	30,54,	
28,52,	2,9,	28,48,	2,10,	
2,11,	32,56,	48,48,	2,12,	
2,13,	14,43,	14,43,	14,43,	
14,43,	14,43,	14,43,	14,43,	
14,43,	14,43,	14,43,	27,50,	
49,60,	2,15,	2,16,	2,17,	
2,18,	2,19,	2,20,	29,48,	
50,61,	51,62,	29,53,	49,48,	
53,64,	27,51,	50,48,	52,48,	
27,48,	52,63,	63,71,	54,48,	
60,48,	53,48,	54,65,	60,67,	
61,48,	61,68,	2,22,	63,48,	
64,48,	69,76,	64,72,	72,48,	
67,74,	73,48,	2,23,	69,48,	
2,24,	67,48,	75,48,	80,48,	
84,48,	2,26,	2,26,	2,26,	
2,26,	2,27,	2,26,	2,26,	
2,26,	2,26,	2,26,	2,26,	
2,26,	2,26,	2,28,	2,26,	
2,29,	2,26,	2,26,	2,30,	
2,26,	2,26,	2,26,	2,26,	
2,26,	2,26,	2,31,	2,32,	
2,33,	2,34,	7,37,	62,69,	
65,73,	8,39,	68,75,	82,48,	
82,85,	70,77,	7,37,	7,37,	
70,48,	8,39,	8,40,	71,78,	
74,79,	65,48,	71,48,	68,48,	
62,48,	62,70,	76,80,	78,82,	
81,84,	77,81,	85,48,	78,48,	
76,48,	74,48,	77,48,	83,48,	
79,83,	83,86,	86,48,	7,38,	
79,48,	81,48,	8,39,	0,0,	
0,0,	0,0,	0,0,	0,0,	
0,0,	0,0,	0,0,	0,0,	
0,0,	7,37,	0,0,	0,0,	
8,39,	21,46,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
21,46,	21,46,	21,46,	0,0,	
0,0,	0,0,	7,37,	0,0,	
0,0,	8,39,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
7,37,	0,0,	7,37,	8,39,	
21,46,	8,39,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
21,46,	21,46,	21,46,	21,46,	
25,48,	25,48,	25,48,	25,48,	
25,48,	25,48,	25,48,	25,48,	
25,48,	25,48,	0,0,	0,0,	
0,0,	0,0,	0,0,	0,0,	
0,0,	25,48,	25,48,	25,48,	
25,48,	25,48,	25,48,	25,48,	
25,48,	25,48,	25,48,	25,48,	
25,48,	25,48,	25,48,	25,48,	
25,48,	25,48,	25,48,	25,48,	
25,48,	25,48,	25,48,	25,48,	
25,48,	25,48,	25,48,	0,0,	
0,0,	0,0,	0,0,	25,48,	
0,0,	25,48,	25,48,	25,48,	
25,48,	25,48,	25,48,	25,48,	
25,48,	25,48,	25,48,	25,48,	
25,48,	25,48,	25,48,	25,48,	
25,48,	25,48,	25,49,	25,48,	
25,48,	25,48,	25,48,	25,48,	
25,48,	25,48,	25,48,	0,0,	
0,0};
struct yysvf yysvec[] = {
0,	0,	0,
yycrank+-1,	0,		0,	
yycrank+-95,	yysvec+1,	0,	
yycrank+0,	0,		yyvstop+1,
yycrank+5,	0,		yyvstop+3,
yycrank+0,	0,		yyvstop+6,
yycrank+4,	0,		yyvstop+8,
yycrank+-221,	0,		yyvstop+10,
yycrank+-224,	0,		yyvstop+12,
yycrank+2,	0,		yyvstop+14,
yycrank+0,	0,		yyvstop+16,
yycrank+0,	0,		yyvstop+19,
yycrank+0,	0,		yyvstop+22,
yycrank+22,	0,		yyvstop+25,
yycrank+93,	0,		yyvstop+28,
yycrank+0,	0,		yyvstop+31,
yycrank+0,	0,		yyvstop+34,
yycrank+2,	0,		yyvstop+37,
yycrank+0,	0,		yyvstop+40,
yycrank+0,	0,		yyvstop+43,
yycrank+3,	0,		yyvstop+46,
yycrank+225,	0,		yyvstop+48,
yycrank+1,	yysvec+21,	yyvstop+51,
yycrank+0,	0,		yyvstop+54,
yycrank+0,	0,		yyvstop+57,
yycrank+300,	0,		yyvstop+60,
yycrank+15,	yysvec+25,	yyvstop+63,
yycrank+54,	yysvec+25,	yyvstop+66,
yycrank+20,	yysvec+25,	yyvstop+69,
yycrank+45,	yysvec+25,	yyvstop+72,
yycrank+17,	yysvec+25,	yyvstop+75,
yycrank+0,	0,		yyvstop+78,
yycrank+13,	0,		yyvstop+81,
yycrank+0,	0,		yyvstop+83,
yycrank+0,	0,		yyvstop+86,
yycrank+0,	yysvec+4,	yyvstop+89,
yycrank+0,	0,		yyvstop+91,
yycrank+0,	yysvec+7,	0,	
yycrank+0,	0,		yyvstop+93,
yycrank+0,	yysvec+8,	0,	
yycrank+0,	0,		yyvstop+95,
yycrank+0,	0,		yyvstop+97,
yycrank+6,	0,		0,	
yycrank+0,	yysvec+14,	yyvstop+99,
yycrank+5,	0,		0,	
yycrank+0,	0,		yyvstop+101,
yycrank+0,	yysvec+21,	yyvstop+103,
yycrank+2,	yysvec+21,	yyvstop+105,
yycrank+24,	yysvec+25,	yyvstop+107,
yycrank+49,	yysvec+25,	yyvstop+109,
yycrank+52,	yysvec+25,	yyvstop+111,
yycrank+47,	yysvec+25,	yyvstop+113,
yycrank+53,	yysvec+25,	yyvstop+115,
yycrank+59,	yysvec+25,	yyvstop+117,
yycrank+57,	yysvec+25,	yyvstop+119,
yycrank+0,	0,		yyvstop+121,
yycrank+0,	0,		yyvstop+123,
yycrank+0,	0,		yyvstop+125,
yycrank+7,	0,		0,	
yycrank+0,	yysvec+21,	yyvstop+127,
yycrank+58,	yysvec+25,	yyvstop+130,
yycrank+62,	yysvec+25,	yyvstop+132,
yycrank+126,	yysvec+25,	yyvstop+134,
yycrank+65,	yysvec+25,	yyvstop+136,
yycrank+66,	yysvec+25,	yyvstop+138,
yycrank+123,	yysvec+25,	yyvstop+140,
yycrank+0,	0,		yyvstop+142,
yycrank+75,	yysvec+25,	yyvstop+144,
yycrank+125,	yysvec+25,	yyvstop+146,
yycrank+73,	yysvec+25,	yyvstop+148,
yycrank+118,	yysvec+25,	yyvstop+150,
yycrank+124,	yysvec+25,	yyvstop+152,
yycrank+69,	yysvec+25,	yyvstop+154,
yycrank+71,	yysvec+25,	yyvstop+157,
yycrank+135,	yysvec+25,	yyvstop+160,
yycrank+76,	yysvec+25,	yyvstop+162,
yycrank+134,	yysvec+25,	yyvstop+165,
yycrank+136,	yysvec+25,	yyvstop+167,
yycrank+133,	yysvec+25,	yyvstop+169,
yycrank+142,	yysvec+25,	yyvstop+171,
yycrank+77,	yysvec+25,	yyvstop+173,
yycrank+143,	yysvec+25,	yyvstop+176,
yycrank+113,	yysvec+25,	yyvstop+178,
yycrank+137,	yysvec+25,	yyvstop+180,
yycrank+78,	yysvec+25,	yyvstop+182,
yycrank+132,	yysvec+25,	yyvstop+185,
yycrank+140,	yysvec+25,	yyvstop+188,
0,	0,	0};
struct yywork *yytop = yycrank+422;
struct yysvf *yybgin = yysvec+1;
char yymatch[] = {
  0,   1,   1,   1,   1,   1,   1,   1, 
  1,   9,  10,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  9,   1,  34,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
 48,  48,  48,  48,  48,  48,  48,  48, 
 48,  48,   1,   1,   1,   1,   1,   1, 
  1,  65,  65,  65,  65,  65,  65,  65, 
 65,  65,  65,  65,  65,  65,  65,  65, 
 65,  65,  65,  65,  65,  65,  65,  65, 
 65,  65,  65,   1,   1,   1,   1,  95, 
  1,  97,  97,  97,  97,  97,  97,  97, 
 97,  97,  97,  97,  97,  97,  97,  97, 
 97,  97,  97,  97,  97,  97,  97,  97, 
 97,  97,  97,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
  1,   1,   1,   1,   1,   1,   1,   1, 
0};
char yyextra[] = {
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,
0};
/*	Copyright (c) 1989 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#pragma ident	"@(#)ncform	6.12	97/12/08 SMI"

int yylineno =1;
# define YYU(x) x
# define NLSTATE yyprevious=YYNEWLINE
struct yysvf *yylstate [YYLMAX], **yylsp, **yyolsp;
char yysbuf[YYLMAX];
char *yysptr = yysbuf;
int *yyfnd;
extern struct yysvf *yyestate;
int yyprevious = YYNEWLINE;
#if defined(__cplusplus) || defined(__STDC__)
int yylook(void)
#else
yylook()
#endif
{
	register struct yysvf *yystate, **lsp;
	register struct yywork *yyt;
	struct yysvf *yyz;
	int yych, yyfirst;
	struct yywork *yyr;
# ifdef LEXDEBUG
	int debug;
# endif
	char *yylastch;
	/* start off machines */
# ifdef LEXDEBUG
	debug = 0;
# endif
	yyfirst=1;
	if (!yymorfg)
		yylastch = yytext;
	else {
		yymorfg=0;
		yylastch = yytext+yyleng;
		}
	for(;;){
		lsp = yylstate;
		yyestate = yystate = yybgin;
		if (yyprevious==YYNEWLINE) yystate++;
		for (;;){
# ifdef LEXDEBUG
			if(debug)fprintf(yyout,"state %d\n",yystate-yysvec-1);
# endif
			yyt = yystate->yystoff;
			if(yyt == yycrank && !yyfirst){  /* may not be any transitions */
				yyz = yystate->yyother;
				if(yyz == 0)break;
				if(yyz->yystoff == yycrank)break;
				}
#ifndef __cplusplus
			*yylastch++ = yych = input();
#else
			*yylastch++ = yych = lex_input();
#endif
#ifdef YYISARRAY
			if(yylastch > &yytext[YYLMAX]) {
				fprintf(yyout,"Input string too long, limit %d\n",YYLMAX);
				exit(1);
			}
#else
			if (yylastch >= &yytext[ yytextsz ]) {
				int	x = yylastch - yytext;

				yytextsz += YYTEXTSZINC;
				if (yytext == yy_tbuf) {
				    yytext = (char *) malloc(yytextsz);
				    memcpy(yytext, yy_tbuf, sizeof (yy_tbuf));
				}
				else
				    yytext = (char *) realloc(yytext, yytextsz);
				if (!yytext) {
				    fprintf(yyout,
					"Cannot realloc yytext\n");
				    exit(1);
				}
				yylastch = yytext + x;
			}
#endif
			yyfirst=0;
		tryagain:
# ifdef LEXDEBUG
			if(debug){
				fprintf(yyout,"char ");
				allprint(yych);
				putchar('\n');
				}
# endif
			yyr = yyt;
			if ( (uintptr_t)yyt > (uintptr_t)yycrank){
				yyt = yyr + yych;
				if (yyt <= yytop && yyt->verify+yysvec == yystate){
					if(yyt->advance+yysvec == YYLERR)	/* error transitions */
						{unput(*--yylastch);break;}
					*lsp++ = yystate = yyt->advance+yysvec;
					if(lsp > &yylstate[YYLMAX]) {
						fprintf(yyout,"Input string too long, limit %d\n",YYLMAX);
						exit(1);
					}
					goto contin;
					}
				}
# ifdef YYOPTIM
			else if((uintptr_t)yyt < (uintptr_t)yycrank) {	/* r < yycrank */
				yyt = yyr = yycrank+(yycrank-yyt);
# ifdef LEXDEBUG
				if(debug)fprintf(yyout,"compressed state\n");
# endif
				yyt = yyt + yych;
				if(yyt <= yytop && yyt->verify+yysvec == yystate){
					if(yyt->advance+yysvec == YYLERR)	/* error transitions */
						{unput(*--yylastch);break;}
					*lsp++ = yystate = yyt->advance+yysvec;
					if(lsp > &yylstate[YYLMAX]) {
						fprintf(yyout,"Input string too long, limit %d\n",YYLMAX);
						exit(1);
					}
					goto contin;
					}
				yyt = yyr + YYU(yymatch[yych]);
# ifdef LEXDEBUG
				if(debug){
					fprintf(yyout,"try fall back character ");
					allprint(YYU(yymatch[yych]));
					putchar('\n');
					}
# endif
				if(yyt <= yytop && yyt->verify+yysvec == yystate){
					if(yyt->advance+yysvec == YYLERR)	/* error transition */
						{unput(*--yylastch);break;}
					*lsp++ = yystate = yyt->advance+yysvec;
					if(lsp > &yylstate[YYLMAX]) {
						fprintf(yyout,"Input string too long, limit %d\n",YYLMAX);
						exit(1);
					}
					goto contin;
					}
				}
			if ((yystate = yystate->yyother) && (yyt= yystate->yystoff) != yycrank){
# ifdef LEXDEBUG
				if(debug)fprintf(yyout,"fall back to state %d\n",yystate-yysvec-1);
# endif
				goto tryagain;
				}
# endif
			else
				{unput(*--yylastch);break;}
		contin:
# ifdef LEXDEBUG
			if(debug){
				fprintf(yyout,"state %d char ",yystate-yysvec-1);
				allprint(yych);
				putchar('\n');
				}
# endif
			;
			}
# ifdef LEXDEBUG
		if(debug){
			fprintf(yyout,"stopped at %d with ",*(lsp-1)-yysvec-1);
			allprint(yych);
			putchar('\n');
			}
# endif
		while (lsp-- > yylstate){
			*yylastch-- = 0;
			if (*lsp != 0 && (yyfnd= (*lsp)->yystops) && *yyfnd > 0){
				yyolsp = lsp;
				if(yyextra[*yyfnd]){		/* must backup */
					while(yyback((*lsp)->yystops,-*yyfnd) != 1 && lsp > yylstate){
						lsp--;
						unput(*yylastch--);
						}
					}
				yyprevious = YYU(*yylastch);
				yylsp = lsp;
				yyleng = yylastch-yytext+1;
				yytext[yyleng] = 0;
# ifdef LEXDEBUG
				if(debug){
					fprintf(yyout,"\nmatch ");
					sprint(yytext);
					fprintf(yyout," action %d\n",*yyfnd);
					}
# endif
				return(*yyfnd++);
				}
			unput(*yylastch);
			}
		if (yytext[0] == 0  /* && feof(yyin) */)
			{
			yysptr=yysbuf;
			return(0);
			}
#ifndef __cplusplus
		yyprevious = yytext[0] = input();
		if (yyprevious>0)
			output(yyprevious);
#else
		yyprevious = yytext[0] = lex_input();
		if (yyprevious>0)
			lex_output(yyprevious);
#endif
		yylastch=yytext;
# ifdef LEXDEBUG
		if(debug)putchar('\n');
# endif
		}
	}
#if defined(__cplusplus) || defined(__STDC__)
int yyback(int *p, int m)
#else
yyback(p, m)
	int *p;
#endif
{
	if (p==0) return(0);
	while (*p) {
		if (*p++ == m)
			return(1);
	}
	return(0);
}
	/* the following are only used in the lex library */
#if defined(__cplusplus) || defined(__STDC__)
int yyinput(void)
#else
yyinput()
#endif
{
#ifndef __cplusplus
	return(input());
#else
	return(lex_input());
#endif
	}
#if defined(__cplusplus) || defined(__STDC__)
void yyoutput(int c)
#else
yyoutput(c)
  int c; 
#endif
{
#ifndef __cplusplus
	output(c);
#else
	lex_output(c);
#endif
	}
#if defined(__cplusplus) || defined(__STDC__)
void yyunput(int c)
#else
yyunput(c)
   int c; 
#endif
{
	unput(c);
	}
