#The CFLAGS variable will be handed down from the top-level makefile.
#CFLAGS = -O2 -ML -GX -DWIN32 -D_WINDOWS -DNEED_CAST

INCPATH = ..\..\include
LIBPATH = ..\..\lib
INCFLAGS = -I. -I$(INCPATH)
LIBS = $(LIBPATH)\aisearch.lib $(LIBPATH)\util.lib

TARGETS = parser.exe

OBJS = parser.obj data.obj run.obj

.cpp.obj:
        $(CC) $(CFLAGS) $(INCFLAGS) -c $*.cpp

all:	$(TARGETS)

parser.exe:       $(OBJS)
        $(CC) $(CFLAGS) $** $(LIBS)

