# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../../..
endif

include $(ROOT)/build/makefile.common

PRODS = \
	qt1 \
	qt2 \
	qt3 \
	qt4 \
	qt5 \
	qt6 \
	qt7 \

# CXXEXTRAFLAGS = 

NOINSTALL = 1

include $(ROOT)/build/makefile.qtsrc2

qt1:	qt1.cpp
qt2:	qt2.cpp
qt3:	qt3.cpp
qt4:	qt4.cpp
qt5:	qt5.cpp
qt6:	qt6.cpp
qt7:	qt7.cpp qt7.h

