#The CFLAGS variable will be passed from the top-level makefile.
#CFLAGS = -P -O2 -mc -DNEED_CAST

INCPATH = ..\..\include
LIBPATH = ..\..\lib
INCFLAGS = -I. -I$(INCPATH)
LIBS = aisearch.lib util.lib

TARGETS = route.exe

OBJS = route.obj

.cc.obj:
        $(CC) $(CFLAGS) $(INCFLAGS) -c $<

all:	$(TARGETS)

route.exe:       $(OBJS)
        $(CC) $(CFLAGS) -L$(LIBPATH) -e$< $** $(LIBS)

