all:
	-(cd src; make; )
	-(cd gnu; make; )
	-(cd exptools; make expmake; )

mymk:
	-(cd src; mymk; )
	-(cd gnu; mymk; )

backup:
	-(cd src; make backup; )
	-(cd gnu; make backup; )
	-(cd exptools; make backup; )

clean:
	-(cd src; make clean; )
	-(cd gnu; make clean; )
	-(cd exptools; make expclean; )

edelf58:
	-(cd src; make; )

gedelf:
	-(cd gnu; make; )

edelf:
	-(cd exptools; make expmake; )

install:
	-(cd exptools; make exptools; )

