#
# Copyright (C) 2010, OMBT LLC and Mike A. Rumore
# All rights reserved.
# Contact: Mike A. Rumore, (mike.a.rumore@gmail.com)
#
all:
	-(cd src; make; )
	-(cd gnu; make; )
	-(cd exptools; make expmake; )

mymk:
	-(cd src; mymk; )
	-(cd gnu; mymk; )

backup:
	-(cd src; make backup; )
	-(cd gnu; make backup; )
	-(cd exptools; make backup; )

clean:
	-(cd src; make clean; )
	-(cd gnu; make clean; )
	-(cd exptools; make expclean; )

edelf58:
	-(cd src; make; )

gedelf:
	-(cd gnu; make; )

edelf:
	-(cd exptools; make expmake; )

install:
	-(cd exptools; make exptools; )

