#
# Copyright (C) 2010, OMBT LLC and Mike A. Rumore
# All rights reserved.
# Contact: Mike A. Rumore, (mike.a.rumore@gmail.com)
#
# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../..
endif

include $(ROOT)/build/makefile.common

SUBDIRS = \
	prop \
	graphoverlap \
	graphoverlap2 \
	graphoverlap3 
	# atp

include $(ROOT)/build/makefile.subdirs
