# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../..
endif

include $(ROOT)/build/makefile.common

SUBDIRS = \
	prop \
	graphoverlap \
	graphoverlap2 \
	graphoverlap3

include $(ROOT)/build/makefile.subdirs
