#!/bin/sh
#	GNU C++ compilation
# Note, ${foo:+foo} is just a weird way of commenting out bar
gcc -c -O -pipe -W -Wall -Wpointer-arith -Wenum-clash -Woverloaded-virtual \
-Wstrict-prototypes -Wmissing-prototypes ${foo:+'-Winline -Wredundant-decls'} \
-finline-functions  -fforce-mem ${foo:+'-funsigned-char -fshort-enums'} \
-fforce-addr -fstrict-prototype -felide-constructors -fno-implicit-templates \
-fomit-frame-pointer -freg-struct-return -msupersparc ${foo:+'-fsave-memoized'} \
-I. -I- $*
