#!/usr/bin/ksh
# find all private files for the given or current 
# directory and all subdirectories.
#
usage() {
cat >&2 <<EOF

usage: $0 [-?] [dir1 [dir2 ...]]

where:
	-? = print usage message.

find all private files in the given directory(s) or use 
the current directory by default. The subdirectories are 
recursively visited.

EOF
}
#
if [[ $# -eq 0 ]]
then
	# just use current directory
	cleartool ls -l -recurse | 
	grep -i 'view *private *object'
elif [[ "${1}" == "-?" ]]
then
	usage
else
	# run for the given list of (presumed) directories.
	for dir in "${@}"
	do
		cleartool ls -l -recurse ${dir} | 
		grep -i 'view *private *object'
	done
fi
#
exit 0
