#
# Copyright (C) 2010, OMBT LLC and Mike A. Rumore
# All rights reserved.
# Contact: Mike A. Rumore, (mike.a.rumore@gmail.com)
#
# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../..
endif

include $(ROOT)/build/makefile.common

PRODS = test1 test2 test3 test4 test5 test6 test7 test8 test9 test10

CXXEXTRAFLAGS = -lrt

TESTLIBS = performance

EXTRALIBS = -lrt

include $(ROOT)/build/makefile.test2

