#!/usr/bin/perl 
#
getMinAndMax();
#
@junk = ($min .. $max);
print "junk is ... @junk\n";
#
print 'last element $junk[-1] is ... ' . $junk[-1] . "\n";
print 'index of last element $#junk is ... ' . $#junk . "\n";
print 'last element $junk[$#junk] is ... ' . $junk[$#junk] . "\n";
#
sub getMinAndMax {
	#
	$min = $max = 0;
	#
	print "enter a min number: ";
	$min = <STDIN>;
	chomp $min;
	#
	print "enter a max number: ";
	$max = <STDIN>;
	chomp $max;
	#
	if ($min > $max)
	{
		# $tmp = $min;
		# $min = $max;
		# $max = $tmp
		($min, $max) = ($max, $min);
	}
}
