#The CFLAGS variable will be handed down from the top-level makefile.
#CFLAGS = -O2 -ML -GX -DWIN32 -D_WINDOWS -DNEED_CAST

INCPATH = ..\..\include
LIBPATH = ..\..\lib
INCFLAGS = -I. -I$(INCPATH)
LIBS = $(LIBPATH)\util.lib

TARGETS = tictac.exe

OBJS = tictac.obj

.cpp.obj:
        $(CC) $(CFLAGS) $(INCFLAGS) -c $*.cpp

all:	$(TARGETS)

tictac.exe:       $(OBJS)
        $(CC) $(CFLAGS) $** $(LIBS)

