# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../..
endif

include $(ROOT)/build/makefile.common

LIBNAME = atomic

HDRS = \
	Atomic.h \
	UseCntBase.h \
	UseCntPtr.h \
	ExtUseCntPtr.h \
	RefCntPtr.h \
	UCBaseObject.h \
	BaseObject.h

include $(ROOT)/build/makefile.lib2

