#
# Copyright (C) 2010, OMBT LLC and Mike A. Rumore
# All rights reserved.
# Contact: Mike A. Rumore, (mike.a.rumore@gmail.com)
#
# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../../..
endif

include $(ROOT)/build/makefile.common

PRODS = \
	t1 \
	t2 \
	t3 \
	t4 \
	t5 \
	t6 \
	t7 \
	t8 \
	t9 \
	t10 \
	t11 \
	t12 \
	t13 \
	t14 \
	t15 \
	t16 \
	t17 \
	t18 \
	t19 \
	t20 \
	t21 \
	t22 \
	t23 \
	t24 \
	t25 \
	t26 \
	t27 \
	t28 \
	t29 \
	t30 \
	t31 \
	t32 \
	t33 \
	t34 \
	t35 \
	t36 \
	t37 \
	t38 \
	t39 \
	t40 \
	t41 \
	t42 \

# CXXEXTRAFLAGS = `pkg-config --cflags --libs gtk+-2.0` 
CXXEXTRAFLAGS = 
CXXLIBFLAGS = `pkg-config --cflags --libs gtk+-2.0` 

NOINSTALL = 1

include $(ROOT)/build/makefile.src2

