#The CFLAGS variable will be handed down from the top-level makefile.
#CFLAGS = -P -O2 -mc -DNEED_CAST

AR = tlib 
AILIB = ..\..\lib\aisearch.lib
INCFLAGS = -I..\..\include

.cc.obj:
        $(CC) $(CFLAGS) $(INCFLAGS) -c $*.cc
        $(AR) $(AILIB) -+$*

OBJS = search.obj astar.obj gbreadth.obj gdepth.obj gucost.obj tbreadth.obj tdepth.obj tucost.obj

all:	$(OBJS)

