#!/usr/bin/perl
#
my $infname = "/dev/tty";
my $outfname = "/dev/tty";
#
$num = @ARGV;
#
if ($num == 1)
{
	($infname) = @ARGV;
}
elsif ($num == 2)
{
	($infname, $outfname) = @ARGV;
}
#
open(IN, $infname) || die("unable to open $infname: $!");
open(OUT, ">$outfname") || die("unable to open $outfname: $!");
#
while ($inbuf = <IN>)
{
	chomp $inbuf;
	print OUT "$inbuf\n";
}
#
close(IN);
close(OUT);
#
