# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../..
endif

include $(ROOT)/build/makefile.common

LIBNAME = gstring

HDRS = \
	gstring.h \
	gstring.cpp \
	trie.h \
	trie.cpp \
	triedata.h \
	triedata.cpp \
	trieindex.h \
	trieindex.cpp

include $(ROOT)/build/makefile.lib2
