#!/usr/bin/perl -w
#
print "Enter your name: ";
$name = <STDIN>;
chomp $name;
#
if ($name eq "Randall")
{
	print "Hello, Randall ... how is the world treating you?\n";
}
else
{
	print "Hello, $name !!!\n";
}
