#!/usr/bin/perl -w
#
%words = qw(
	fred camel
	barney llama
	betty alpaca
	wilma alpaca
);
#
print "Enter your name: ";
$name = <STDIN>;
chomp $name;
#
if ($name eq "Randall")
{
	print "Hello, Randall ... how is the world treating you?\n";
}
else
{
	print "Hello, $name ...\n";
	$secretword = $words{$name};
	if ($secretword eq "")
	{
		# default passwd
		$secretword = "duck";
	}
	print "What is the secret passwd? ";
	$guess = <STDIN>;
	chomp $guess;
	while ($guess ne $secretword)
	{
		print "Wrong, try again ... \n";
		print "What is the secret passwd? ";
		$guess = <STDIN>;
		chomp $guess;
	}
	print "You're in, $name !!!\n";
}
