#!/usr/bin/perl
#
%words = qw(
	fred camel
	barney llama
	betty alpaca
	wilma alpaca
);
#
print "Enter your name: ";
$name = <STDIN>;
chomp $name;
#
if ($name =~ /^randall\b/i)
{
	print "Hello, Randall ... how is the world treating you?\n";
}
else
{
	print "Hello, $name ...\n";
	print "What is the secret passwd? ";
	$guess = <STDIN>;
	chomp $guess;
	while (! good_word($name, $guess))
	{
		print "Wrong, try again ... \n";
		print "What is the secret passwd? ";
		$guess = <STDIN>;
		chomp $guess;
	}
	print "You're in, $name !!!\n";
}

sub good_word {
	my($somename, $someguess) = @_;
	$somename =~ s/\W.*//;
	$somename =~ tr/A-Z/a-z/;
	#
	if ($somename eq "randall")
	{
		return 1;
	}
	elsif (($words{$somename} || "duck") eq $someguess)
	{
		return 1;
	}
	else
	{
		return 0;
	}
}
