#!/usr/bin/perl
#
($min, $max) = getdata();
#
$total = sum(($min .. $max));
#
print "$min+...+$max = $total\n";
#
sub sum {
	my $sum = 0;
	foreach (@_)
	{
		$sum += $_;
	}
	return $sum;
}
sub getdata {
	my $min = 0;
	my $max = 0;
	#
	print "enter min: ";
	$min = <STDIN>;
	chomp $min;
	#
	print "enter max: ";
	$max = <STDIN>;
	chomp $max;
	#
	if ($max < $min)
	{
		($min, $max) = ($max, $min);
	}
	#
	return ($min, $max);
}
