#
# Copyright (C) 2010, OMBT LLC and Mike A. Rumore
# All rights reserved.
# Contact: Mike A. Rumore, (mike.a.rumore@gmail.com)
#
all:	
	-(cd cfdmp; make all;)
	-(cd f2lns; make all;)
	-(cd ftrc; make all;)
	-(cd lnno; make all;)
	-(cd html_examples; make all;)

clean:	
	-(cd cfdmp; make clean;)
	-(cd f2lns; make clean;)
	-(cd ftrc; make clean;)
	-(cd lnno; make clean;)
	-(cd html_examples; make clean;)
