#!/usr/bin/perl
#ex_11-1
#Learning Perl Appendix A, Exercise 11.1
open(PW,"/etc/passwd") || die "How did you get logged in?";
while (<PW>) {
    ($user,$uid,$gcos) = (split /:/)[0,2,4];
    ($real) = split /,/,$gcos;
    write;
}
format STDOUT =
@<<<<<<< @>>>>>> @<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
$user, $uid, $real
.
#ex_11-2
#Learning Perl Appendix A, Exercise 11.2
# append to program from the first problem...
format STDOUT_TOP =
Username User ID Real Name
======== ======= =========
.
#ex_11-3
#Learning Perl Appendix A, Exercise 11.3
# append to program from the first problem...
format STDOUT_TOP =
Page @<<<
$%
Username User ID Real Name
======== ======= =========
.
