#
# Copyright (C) 2010, OMBT LLC and Mike A. Rumore
# All rights reserved.
# Contact: Mike A. Rumore, (mike.a.rumore@gmail.com)
#
# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../..
endif

include $(ROOT)/build/makefile.common

PERLSCRIPTS = \
	frame \
	grid \
	grid2 \
	hello_world \
	slider \
	text_button \
	text_label_button \
	text \
	dialogbox \
	topwindow \
	radio \
	check \
	listbox \
	menu \
	optionmenu \
	canvas \
	adjuster \
	scrolled \
	scrolled2 \
	pack \
	callbacks \
	table \
	tablematrix \
	tabs \
	progressbar \
	dateentry \
	spiral \

include $(ROOT)/build/makefile.PL
