# ROOT = /home/ombt/ombt

ifndef ROOT
$(error ROOT is not set)
endif

include $(ROOT)/build/makefile.common

PRODS = timer1 timer2 timer3 timer4 timer5

CXXEXTRAFLAGS = -lombttimers

include $(ROOT)/build/makefile.test
