# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../..
endif

include $(ROOT)/build/makefile.common

LIBNAME = interpolation

HDRS = CubicSpline.h CubicSpline.cpp

include $(ROOT)/build/makefile.lib2
