# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/../..
endif

include $(ROOT)/build/makefile.common

PRODS = \
	test1 \
	test2 \
	test3 \
	test4 \
	test5 \
	test6 \
	test7 \
	test8 \
	test9 \
	test10 \
	test11 \
	test12 \
	test13 \
	test14 \
	test15 \
	test16

CXXEXTRAFLAGS = 
CXXLIBFLAGS = -pthread -lombtthreads -lombtlogging -lombtrandom

include $(ROOT)/build/makefile.test
