#!/usr/bin/perl -w
use strict;
#
# roll some dice and print faces
#
my $faces;
my %faces;
#
@faces{ (1..6) } = (
	\(
		"#######\n",
		"#     #\n",
		"#  1  #\n",
		"#     #\n",
		"#######\n"
	),
	\(
		"#######\n",
		"# 2   #\n",
		"#     #\n",
		"#   2 #\n",
		"#######\n"
	),
	\(
		"#######\n",
		"# 3   #\n",
		"#  3  #\n",
		"#   3 #\n",
		"#######\n"
	),
	\(
		"#######\n",
		"# 4 4 #\n",
		"#     #\n",
		"# 4 4 #\n",
		"#######\n"
	),
	\(
		"#######\n",
		"# 5 5 #\n",
		"#  5  #\n",
		"# 5 5 #\n",
		"#######\n"
	),
	\(
		"#######\n",
		"# 6 6 #\n",
		"# 6 6 #\n",
		"# 6 6 #\n",
		"#######\n"
	)
);
#
foreach my $face (keys %faces)
{
	print "$face:\n";
	print "$faces{$face}\n";
}
#
exit 0
