#!/usr/bin/perl -w
use strict;
#
my $faqdir = "/opt/exp/perl/lib/5.00503/pod";
#
my @faqfiles = qw (
	perlfaq.pod perlfaq1.pod perlfaq2.pod perlfaq3.pod
	perlfaq4.pod perlfaq5.pod perlfaq6.pod perlfaq7.pod
	perlfaq8.pod perlfaq9.pod
);
#
my $pattern = "";
#
$pattern = $ARGV[0] || die "pattern not given: $!";
#
for my $faqname (@faqfiles)
{
	open(FAQFILE, "$faqdir/$faqname") || 
		die "can not open $faqdir/$faqname: $!";
	#
	while (<FAQFILE>)
	{
		if (s/^=head2// and m/$pattern/)
		{
			print "$faqname:\n$_";
		}
	}
	#
	close(FAQFILE);
}
#
exit 0
