#All variables needed by this makefile are set by the top-level makefile.

OBJS = aosearch.o taobread.o taodepth.o

all:    $(OBJS)
	$(AR) $(AILIB) $(OBJS)
ifdef RANLIB
	$(RANLIB) $(AILIB)
endif

clean:
	rm -f $(OBJS)

