# ROOT = /home/ombt/ombt

ifndef ROOT
$(error ROOT is not set)
endif

include $(ROOT)/build/makefile.common

LIBNAME = interpolation

HDRS = CubicSpline.h CubicSpline.cpp

include $(ROOT)/build/makefile.lib2
